# Generated by Django 5.2.7 on 2025-10-12 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_orderitem_subtotal_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
